# Generated by Django 5.0.6 on 2025-08-09 11:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('national_id', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('relation', models.CharField(choices=[('mother', 'الأم'), ('father', 'الأب'), ('spouse', 'الزوج/الزوجة'), ('son', 'الابن/الابنة'), ('other', 'أخرى')], max_length=20)),
                ('documents', models.FileField(upload_to='documents/')),
                ('terms_accepted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('appointment_datetime', models.DateTimeField(blank=True, null=True)),
                ('appointment_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
