# Generated by Django 5.0.6 on 2025-08-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrequest',
            name='inmate_id',
            field=models.CharField(default='0000000000', max_length=20),
            preserve_default=False,
        ),
    ]
